name: jwt_server
description: A JWT-authenticated "Hello World" HTTP server.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  dart_jsonwebtoken: ^2.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
